// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxS-CdRbO8KnhTmYG2KxlAfii1eJ68aN8',
    appId: '1:424917559272:web:ead24f045e69f6346ba65d',
    messagingSenderId: '424917559272',
    projectId: 'school-app-b2ff7',
    authDomain: 'school-app-b2ff7.firebaseapp.com',
    storageBucket: 'school-app-b2ff7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRz9zJVIwD2msiNuCPb-Ay6YJWywJRUJ0',
    appId: '1:424917559272:android:5a8c00c9b4995e8b6ba65d',
    messagingSenderId: '424917559272',
    projectId: 'school-app-b2ff7',
    storageBucket: 'school-app-b2ff7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7VbMPet91vMDTEX-2CkwCmsBSOZs1HI',
    appId: '1:424917559272:ios:007e4c5c6b3fbb4f6ba65d',
    messagingSenderId: '424917559272',
    projectId: 'school-app-b2ff7',
    storageBucket: 'school-app-b2ff7.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk7VbMPet91vMDTEX-2CkwCmsBSOZs1HI',
    appId: '1:424917559272:ios:007e4c5c6b3fbb4f6ba65d',
    messagingSenderId: '424917559272',
    projectId: 'school-app-b2ff7',
    storageBucket: 'school-app-b2ff7.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxS-CdRbO8KnhTmYG2KxlAfii1eJ68aN8',
    appId: '1:424917559272:web:80fe7247ebc6de4a6ba65d',
    messagingSenderId: '424917559272',
    projectId: 'school-app-b2ff7',
    authDomain: 'school-app-b2ff7.firebaseapp.com',
    storageBucket: 'school-app-b2ff7.firebasestorage.app',
  );

}